<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/06/09 10:21:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
